[package]
name = "surrealdb"
version = "0.1.0"
authors = ["Maxwell Flitton <maxwellflitton@gmail.com>"]
edition = "2018"

[dependencies]
surrealdb = "1.0.0-beta.9+20230402"
serde = "1.0.164"
tokio = { version = "1", features = ["full"] }

[lib]
name = "rust_surrealdb"
crate-type=["cdylib"]

[dependencies.pyo3]
version = "0.19.0"
features = ["extension-module"]
